// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpoKHsCWDIeGqhioFUoxwx6bd5LJeLiN4',
    appId: '1:627395477669:web:a6656c0018be852816cd4c',
    messagingSenderId: '627395477669',
    projectId: 'mynotes-flutter-project-v1',
    authDomain: 'mynotes-flutter-project-v1.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQ_jqoMJwLQb_eD4-EDECJJuV_EPnMQ4',
    appId: '1:627395477669:android:1e3e0f8f6324b3a216cd4c',
    messagingSenderId: '627395477669',
    projectId: 'mynotes-flutter-project-v1',
    storageBucket: 'mynotes-flutter-project-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAJ3QBO2kC94kSfy5l3HlUa96zl9rgc8',
    appId: '1:627395477669:ios:536f347bb43afaa916cd4c',
    messagingSenderId: '627395477669',
    projectId: 'mynotes-flutter-project-v1',
    storageBucket: 'mynotes-flutter-project-v1.appspot.com',
    iosClientId: '627395477669-1st9d21lak50o66c1gucubj5gqtts46l.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANAJ3QBO2kC94kSfy5l3HlUa96zl9rgc8',
    appId: '1:627395477669:ios:536f347bb43afaa916cd4c',
    messagingSenderId: '627395477669',
    projectId: 'mynotes-flutter-project-v1',
    storageBucket: 'mynotes-flutter-project-v1.appspot.com',
    iosClientId: '627395477669-1st9d21lak50o66c1gucubj5gqtts46l.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart',
  );
}
